clusterGroup:
  name: hub
  isHubCluster: true
  # Note: setting this to true stores the vault unseal keys inside a cluster secret and
  # is fundamentally insecure
  insecureUnsealVaultInsideCluster: true

  namespaces:
  - busybox

  projects:
  - busybox

  applications:
    busybox:
      name: busybox
      namespace: busybox
      project: busybox
      path: charts/all/busybox