clusterGroup:
  name: hub
  isHubCluster: true
  # Note: setting this to true stores the vault unseal keys inside a cluster secret and
  # is fundamentally insecure
  insecureUnsealVaultInsideCluster: true

  namespaces:
  - config-demo
  - busybox

  projects:
  - config-demo
  - busybox

  applications:
    config-demo:
      name: config-demo
      namespace: config-demo
      project: config-demo
      path: charts/all/config-demo

    busybox:
      name: busybox
      namespace: busybox
      project: busybox
      path: charts/all/busybox